#!/bin/bash
docker run --rm=true -v $(pwd):/data ubuntu /bin/bash -c "apt update && apt install -y gcc build-essential git && mkdir /work && cd /work && git clone https://github.com/gissehel/dudumper && cd /work/dudumper/src && make clean all && strip dudumper && cp /work/dudumper/src/dudumper /data/dudumper && echo 'All is OK...'"
